const translations = {
  en: {
    common: {
      homeLabel: "App Pages home",
      back: "← Back to CopyManager",
      languageLabel: "Choose language",
      copyright: "© 2026 CopyManager"
    },
    home: {
      title: "CopyManager · Documentation and Support",
      description: "User guide, privacy policy, terms, and support information for CopyManager.",
      eyebrow: "LOCAL FIRST",
      heading: "Everything you copied,<br>ready when you need it.",
      lead: "Cross-platform clipboard history, search, favorites, previews, and auto-paste, with history stored locally by default.",
      viewDocuments: "View documents",
      documentsEyebrow: "DOCUMENTS",
      documentsTitle: "Documents and support",
      guideTitle: "User Guide",
      guideText: "Getting started, core features, and platform permissions",
      privacyTitle: "Privacy Policy",
      privacyText: "Clipboard data, network requests, and iCloud sync",
      termsTitle: "Terms of Service",
      termsText: "Usage rules, service boundaries, and liability",
      supportTitle: "Get Support",
      supportText: "FAQs, troubleshooting, and contact information"
    },
    guide: {
      title: "CopyManager User Guide",
      description: "CopyManager user guide.",
      eyebrow: "USER GUIDE",
      heading: "CopyManager User Guide",
      meta: "Updated: July 25, 2026",
      startTitle: "1. Getting Started",
      startText: "After launching CopyManager, copy text, images, or files normally to create history entries. Open the main window with the global shortcut, then find content by search, type filter, or source application.",
      pasteTitle: "2. Pasting and Favorites",
      pasteText: "Selecting a history item puts it back on the system clipboard. With auto-paste enabled, CopyManager also tries to send the system paste shortcut to the previous application. Add frequently used content to favorites so normal history cleanup does not remove it.",
      protectionTitle: "3. Privacy Protection",
      protectionText: "Enable sensitive-content protection in Settings to ignore clipboard data marked as sensitive and to exclude apps by name or identifier. You can pause monitoring or clear history at any time.",
      syncTitle: "4. Import, Export, and Sync",
      syncText: "Use Import/Export to back up or restore local history. The Mac App Store build can also enable private iCloud sync; only text and image history is synced, not file entries, file paths, or source-app information.",
      supportTitle: "5. Get Support",
      supportText: "If you have a problem, see <a data-local-link href=\"support.html\">Help and Feedback</a>. To contact support, email <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> and avoid attaching unnecessary sensitive clipboard content."
    },
    privacy: {
      title: "CopyManager Privacy Policy",
      description: "CopyManager Privacy Policy covering clipboard data, local storage, network requests, and optional iCloud sync.",
      eyebrow: "PRIVACY POLICY",
      heading: "CopyManager Privacy Policy",
      meta: "Effective: July 18, 2026 · Updated: July 25, 2026",
      intro: "CopyManager (the “Software”) is a cross-platform clipboard history manager. This policy explains how the Software handles data while providing clipboard capture, search, previews, auto-paste, feedback, and related features.",
      clipboardTitle: "1. Clipboard Data",
      clipboardText: "While the Software is running with clipboard monitoring enabled, it processes text, images, local file paths, and source-application names that you actively copy. Content marked sensitive by password managers or as temporary clipboard data is ignored; you can also exclude additional applications.",
      storageTitle: "2. Local Storage",
      storageText: "By default, clipboard history is stored on your local device. Text and metadata are kept in a SQLite database, and original images in a local media directory. You may pause monitoring, delete individual items, or clear history at any time. Uninstalling the Software or deleting its local data removes device history.",
      icloudTitle: "3. Optional iCloud Sync",
      icloudText: "The Mac App Store build lets you enable iCloud sync. When enabled, text and image history is stored in your private CloudKit database for syncing between devices using the same Apple Account. File entries, file paths, and source-app information are not uploaded. Apple handles iCloud and CloudKit under its policies. The direct-download build does not offer iCloud sync.",
      networkTitle: "4. Network Requests and Support Data",
      network1: "When you submit feedback, your name (optional), email, feedback, software version, and operating-system version are sent to CopyManager support.",
      network2: "The direct-download build contacts CopyManager services for license validation and update checks. Once daily, it also sends an activity record containing a random installation ID, operating system, CPU architecture, software version, and activation code when present.",
      network3: "The Mac App Store build uses Apple StoreKit for purchases and does not include direct-download licensing, self-update, or activity reporting.",
      networkText: "These requests never contain clipboard content. We do not sell clipboard data or use third-party advertising or cross-app tracking SDKs.",
      permissionsTitle: "5. System Permissions",
      permissionsText: "Auto-paste is optional. On macOS, Accessibility permission is required only when you use it, so the Software can send the paste shortcut. Denying permission does not affect copying or clipboard history.",
      choicesTitle: "6. Your Choices",
      choicesText: "You can pause clipboard monitoring, disable sensitive-content protection or iCloud sync, clear history, and revoke permissions in system settings. Before submitting feedback, remove any information you do not want to send.",
      updatesTitle: "7. Policy Updates",
      updatesText: "If features or data practices change, this policy may be updated and the updated date will be shown on this page.",
      contactTitle: "8. Contact Us",
      contactText: "For questions about this policy or data processing, email <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> or visit <a data-local-link href=\"support.html\">Help and Feedback</a>."
    },
    terms: {
      title: "CopyManager Terms of Service",
      description: "CopyManager Terms of Service.",
      eyebrow: "TERMS OF SERVICE",
      heading: "CopyManager Terms of Service",
      meta: "Effective: December 18, 2025 · Updated: July 25, 2026",
      intro: "Please read these terms before using CopyManager (the “Software”). By downloading, installing, or using the Software, you agree to them. If you disagree, stop using the Software.",
      serviceTitle: "1. Service Description",
      serviceText: "The Software provides clipboard history, search, favorites, previews, auto-paste, import and export, plus licensing, purchasing, or iCloud sync in certain builds. Features may vary by build, operating system, permissions, device capabilities, and service availability.",
      rulesTitle: "2. Usage Rules",
      rulesText: "Use the Software lawfully and take responsibility for content you copy, store, process, or share. Do not use it to infringe rights, violate applicable law, disrupt the Software or related services, or perform attacks or abuse prohibited by law.",
      contentTitle: "3. Clipboard Content and Backups",
      contentText: "Clipboard history may contain passwords, personal information, or other sensitive content. Decide what is appropriate to store, regularly remove sensitive records, and keep necessary backups. Before deleting history, local databases, app data, or cloud data, confirm that you have retained what you need.",
      autopasteTitle: "4. Auto-Paste and Platform Limits",
      autopasteText: "Auto-paste depends on operating-system permissions, the focused window, and platform input capabilities. macOS requires Accessibility permission; Linux Wayland may require extra tools and remains subject to system limits. Auto-paste is not guaranteed in every app, device, or system environment.",
      purchaseTitle: "5. Purchases, Licenses, and Refunds",
      purchaseText: "Paid features, licenses, and purchases for the direct-download build follow the rules shown on the purchase page. Mac App Store purchases and restoration use Apple StoreKit, and Apple's terms apply to transactions and refunds. Confirm the build, platform, and license scope before purchase.",
      licenseTitle: "6. Open-Source Licenses and Intellectual Property",
      licenseText: "The Software source code and third-party components are governed by their included open-source and third-party licenses; rights granted by those licenses are not limited by these terms. The CopyManager name, graphics, and materials not provided under open-source licenses are protected by applicable intellectual-property law.",
      disclaimerTitle: "7. Disclaimer and Limitation of Liability",
      disclaimerText: "To the maximum extent permitted by law, the Software is provided “as is” and “as available,” without a promise of uninterrupted, error-free operation or fitness for every purpose. The developer is liable only as required by law for data loss, paste failures, or other loss caused by device failure, user error, permission limits, third-party service failures, or force majeure.",
      updatesTitle: "8. Updates and Stopping Use",
      updatesText: "We may update these terms for functional, legal, or operational changes and will show the update date on this page. You may stop using and uninstall the Software at any time.",
      contactTitle: "9. Contact Us",
      contactText: "For questions about these terms, email <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> or visit <a data-local-link href=\"support.html\">Help and Feedback</a>."
    },
    support: {
      title: "CopyManager Help and Feedback",
      description: "CopyManager help and feedback for clipboard monitoring, auto-paste, history data, and common issues.",
      eyebrow: "SUPPORT",
      heading: "CopyManager Help and Feedback",
      meta: "Updated: July 25, 2026",
      captureTitle: "Why isn't copied content being recorded?",
      captureText: "Make sure CopyManager is running and clipboard monitoring is not paused. Password-manager content, data marked sensitive or temporary, and apps excluded in Settings are not added to history.",
      autopasteTitle: "Why isn't auto-paste working?",
      autopasteText: "On macOS, allow CopyManager under System Settings → Privacy & Security → Accessibility. Linux X11 uses XTest; Wayland requires an available <code>wtype</code> or <code>ydotool</code> and may still be restricted by desktop security policies. Copying to the system clipboard works even when auto-paste is unavailable.",
      storageTitle: "Where is history stored?",
      storageText: "Text and metadata are stored in a local SQLite database, and images in a local media directory. Use Import/Export in the app to back up and restore history. The Mac App Store build can also enable private iCloud sync.",
      deleteTitle: "How do I delete data?",
      deleteText: "You can delete individual items, run rule-based cleanup, or clear history in the app. Export anything you want to keep before an irreversible cleanup.",
      contactTitle: "Contact Support",
      contactText: "Email <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> with your operating system, CopyManager version, when the issue occurred, and steps to reproduce it. Do not send passwords, tokens, or unnecessary private clipboard content.",
      relatedTitle: "Related Documents",
      relatedText: "You can also read the <a data-local-link href=\"user-guide.html\">User Guide</a>, <a data-local-link href=\"privacy-policy.html\">Privacy Policy</a>, and <a data-local-link href=\"terms-of-service.html\">Terms of Service</a>."
    }
  },
  zh_CN: {
    common: { homeLabel: "App Pages 首页", back: "← 返回 CopyManager", languageLabel: "选择语言", copyright: "© 2026 CopyManager" },
    home: { title: "CopyManager · 产品文档与支持", description: "CopyManager 的使用说明、隐私政策、用户协议与支持信息。", eyebrow: "本地优先", heading: "复制过的内容，<br>随时找回来。", lead: "跨平台剪贴板历史、搜索、收藏、预览与自动粘贴，默认将历史保存在本地设备。", viewDocuments: "查看文档", documentsEyebrow: "文档", documentsTitle: "文档与支持", guideTitle: "使用说明", guideText: "快速入门、核心功能与平台权限", privacyTitle: "隐私政策", privacyText: "了解剪贴板数据、网络请求与 iCloud 同步", termsTitle: "用户协议", termsText: "了解使用规则、服务边界与责任说明", supportTitle: "获取支持", supportText: "常见问题、故障排查与联系方式" },
    guide: { title: "CopyManager 使用说明", description: "CopyManager 使用说明。", eyebrow: "使用说明", heading: "CopyManager 使用说明", meta: "更新日期：2026 年 7 月 25 日", startTitle: "1. 开始使用", startText: "启动 CopyManager 后，正常复制文本、图片或文件即可生成历史。使用全局快捷键打开主窗口，通过搜索、类型筛选和来源应用快速找到内容。", pasteTitle: "2. 粘贴与收藏", pasteText: "选择历史条目可将内容放回系统剪贴板；启用自动粘贴后，还会尝试向之前的应用发送系统粘贴快捷键。常用内容可以加入收藏，避免在清理普通历史时丢失。", protectionTitle: "3. 隐私保护", protectionText: "在设置中开启敏感内容保护，可忽略带有敏感标记的剪贴板内容，并按应用名称或标识符添加排除项。你可以随时暂停监听或清空历史。", syncTitle: "4. 导入、导出与同步", syncText: "使用“导入/导出”备份或恢复本地历史。Mac App Store 版本还可以主动开启私有 iCloud 同步；同步只包含文本与图片历史，不包含文件条目、文件路径或来源应用信息。", supportTitle: "5. 获取支持", supportText: "遇到问题时请查看<a data-local-link href=\"support.html\">帮助与反馈</a>。如需联系支持，请发送邮件至 <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>，并避免附上不必要的敏感剪贴板内容。" },
    privacy: { title: "CopyManager 隐私政策", description: "CopyManager 隐私政策：了解剪贴板数据、本地存储、网络请求与可选 iCloud 同步。", eyebrow: "隐私政策", heading: "CopyManager 隐私政策", meta: "生效日期：2026 年 7 月 18 日 · 更新日期：2026 年 7 月 25 日", intro: "CopyManager（以下简称“本软件”）是一款跨平台剪贴板历史管理工具。本政策说明本软件在提供剪贴板记录、搜索、预览、自动粘贴、反馈及相关功能时如何处理数据。", clipboardTitle: "1. 剪贴板数据", clipboardText: "本软件运行并启用剪贴板监听时，会处理你主动复制的文本、图片、本地文件路径以及来源应用名称。带有密码管理器或临时剪贴板敏感标记的内容会被忽略；你也可以配置额外排除的应用。", storageTitle: "2. 本地存储", storageText: "默认情况下，剪贴板历史保存在你的本地设备。文本和元数据保存在 SQLite 数据库中，图片原图保存在本地媒体目录中。你可以随时暂停监听、删除单个条目或清空历史；卸载本软件或删除相关本地数据会移除设备上的历史。", icloudTitle: "3. 可选 iCloud 同步", icloudText: "Mac App Store 版本允许你主动开启 iCloud 同步。开启后，文本和图片历史会保存到你的私有 CloudKit 数据库，以便在使用同一 Apple 账户的设备间同步；文件条目、文件路径和来源应用信息不会上传。iCloud 与 CloudKit 由 Apple 按其政策处理。直装版本不提供 iCloud 同步。", networkTitle: "4. 网络请求与支持数据", network1: "你主动提交反馈时，姓名（可选）、邮箱、反馈内容、软件版本和操作系统版本会发送到 CopyManager 支持服务。", network2: "直装版本会访问 CopyManager 服务进行许可证校验和更新检查，并每日发送一次活动记录，其中包含随机安装 ID、操作系统、CPU 架构、软件版本以及存在时的激活码。", network3: "Mac App Store 版本使用 Apple StoreKit 处理购买，不包含直装许可证、自更新和活动上报功能。", networkText: "上述请求不包含剪贴板内容。我们不会出售剪贴板数据，也不使用第三方广告或跨应用跟踪 SDK。", permissionsTitle: "5. 系统权限", permissionsText: "自动粘贴是可选功能。在 macOS 上，仅当你使用该功能时才需要 Accessibility（辅助功能）权限，以发送粘贴快捷键。拒绝该权限不会影响复制和剪贴板历史功能。", choicesTitle: "6. 你的选择", choicesText: "你可以暂停剪贴板监听、关闭敏感内容保护或 iCloud 同步、清理历史记录，并通过系统设置撤销相关权限。提交反馈前，你可以自行删除不希望发送的信息。", updatesTitle: "7. 政策更新", updatesText: "如果功能或数据处理方式发生变化，本政策可能相应更新，并在本页面标注更新日期。", contactTitle: "8. 联系我们", contactText: "如对本政策或数据处理有疑问，请发送邮件至 <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>，或查看<a data-local-link href=\"support.html\">帮助与反馈</a>。" },
    terms: { title: "CopyManager 用户协议", description: "CopyManager 用户协议。", eyebrow: "用户协议", heading: "CopyManager 用户协议", meta: "生效日期：2025 年 12 月 18 日 · 更新日期：2026 年 7 月 25 日", intro: "在使用 CopyManager（以下简称“本软件”）之前，请仔细阅读本协议。下载、安装或使用本软件，即表示你同意本协议；如不同意，请停止使用。", serviceTitle: "1. 服务说明", serviceText: "本软件提供剪贴板历史、搜索、收藏、预览、自动粘贴、导入导出以及特定版本中的许可证、购买或 iCloud 同步功能。实际功能可能因软件版本、操作系统、系统权限、设备能力和相关服务状态而有所不同。", rulesTitle: "2. 使用规则", rulesText: "你应当合法使用本软件，并对自行复制、保存、处理或分享的内容负责。不得利用本软件侵犯他人权利、违反适用法律、干扰软件或相关服务的正常运行，也不得实施法律禁止的攻击或滥用。", contentTitle: "3. 剪贴板内容与备份", contentText: "剪贴板历史可能包含密码、个人信息或其他敏感内容。你应自行决定哪些内容适合保存，并建议定期清理敏感记录及保留必要备份。删除历史、本地数据库、应用数据或云端数据前，请先确认已保留所需内容。", autopasteTitle: "4. 自动粘贴与平台限制", autopasteText: "自动粘贴依赖操作系统权限、当前焦点窗口和平台输入能力。macOS 需要 Accessibility 权限；Linux Wayland 可能需要额外工具且存在系统限制。本软件不保证自动粘贴在所有应用、设备或系统环境中均可用。", purchaseTitle: "5. 购买、许可证与退款", purchaseText: "直装版本的付费功能、许可证和购买由购买页面展示的规则约束。Mac App Store 版本的购买与恢复购买通过 Apple StoreKit 处理，交易和退款适用 Apple 的相关条款。购买前请确认版本、平台和授权范围。", licenseTitle: "6. 开源许可与知识产权", licenseText: "本软件源代码及第三方组件分别受随附的开源许可证和第三方许可约束；这些许可授予的权利不受本协议限制。CopyManager 的名称、图形及未按开源许可提供的材料受适用的知识产权法律保护。", disclaimerTitle: "7. 免责声明与责任限制", disclaimerText: "在适用法律允许的最大范围内，本软件按“现状”和“可用”状态提供，不承诺始终不中断、完全无误或满足所有特定用途。对于因设备故障、误操作、权限限制、第三方服务异常或不可抗力造成的数据丢失、粘贴失败或其他损失，开发者仅在法律规定的范围内承担责任。", updatesTitle: "8. 协议更新与停止使用", updatesText: "我们可能因功能、法律或运营变化更新本协议，并在本页面标注更新日期。你可以随时停止使用并卸载本软件。", contactTitle: "9. 联系我们", contactText: "如对本协议有疑问，请发送邮件至 <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>，或查看<a data-local-link href=\"support.html\">帮助与反馈</a>。" },
    support: { title: "CopyManager 帮助与反馈", description: "CopyManager 帮助与反馈：剪贴板监听、自动粘贴、历史数据与常见问题。", eyebrow: "支持", heading: "CopyManager 帮助与反馈", meta: "更新日期：2026 年 7 月 25 日", captureTitle: "为什么没有记录复制内容？", captureText: "请确认 CopyManager 正在运行且剪贴板监听没有暂停。密码管理器、带有敏感或临时标记的内容，以及你在设置中排除的应用不会写入历史。", autopasteTitle: "为什么自动粘贴没有生效？", autopasteText: "macOS 用户需要在“系统设置 → 隐私与安全性 → 辅助功能”中允许 CopyManager。Linux X11 使用 XTest；Wayland 环境需要可用的 <code>wtype</code> 或 <code>ydotool</code>，且仍可能受桌面环境安全策略限制。即使无法自动粘贴，复制到系统剪贴板仍可正常使用。", storageTitle: "历史数据保存在哪里？", storageText: "文本和元数据保存在本地 SQLite 数据库中，图片保存在本地媒体目录。你可以使用应用内导入/导出功能备份和恢复历史。Mac App Store 版本还可由你主动开启私有 iCloud 同步。", deleteTitle: "如何删除数据？", deleteText: "你可以在应用中删除单个条目、按规则自动清理或清空历史。执行不可撤销的清理前，请先导出需要保留的数据。", contactTitle: "联系支持", contactText: "请发送邮件至 <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>，并说明操作系统、CopyManager 版本、问题发生时间和复现步骤。请勿发送密码、令牌或不必要的剪贴板隐私内容。", relatedTitle: "相关文档", relatedText: "你还可以查看<a data-local-link href=\"user-guide.html\">使用说明</a>、<a data-local-link href=\"privacy-policy.html\">隐私政策</a>和<a data-local-link href=\"terms-of-service.html\">用户协议</a>。" }
  }
};

translations.zh_TW = {
  common: { homeLabel: "App Pages 首頁", back: "← 返回 CopyManager", languageLabel: "選擇語言", copyright: "© 2026 CopyManager" },
  home: { title: "CopyManager · 產品文件與支援", description: "CopyManager 的使用說明、隱私權政策、使用者協議與支援資訊。", eyebrow: "本機優先", heading: "複製過的內容，<br>隨時找回來。", lead: "跨平台剪貼簿歷史、搜尋、收藏、預覽與自動貼上，預設將歷史儲存在本機裝置。", viewDocuments: "查看文件", documentsEyebrow: "文件", documentsTitle: "文件與支援", guideTitle: "使用說明", guideText: "快速入門、核心功能與平台權限", privacyTitle: "隱私權政策", privacyText: "瞭解剪貼簿資料、網路請求與 iCloud 同步", termsTitle: "使用者協議", termsText: "瞭解使用規則、服務範圍與責任說明", supportTitle: "取得支援", supportText: "常見問題、故障排除與聯絡方式" },
  guide: { title: "CopyManager 使用說明", description: "CopyManager 使用說明。", eyebrow: "使用說明", heading: "CopyManager 使用說明", meta: "更新日期：2026 年 7 月 25 日", startTitle: "1. 開始使用", startText: "啟動 CopyManager 後，正常複製文字、圖片或檔案即可產生歷史。使用全域快速鍵開啟主視窗，透過搜尋、類型篩選和來源應用程式快速找到內容。", pasteTitle: "2. 貼上與收藏", pasteText: "選擇歷史項目可將內容放回系統剪貼簿；啟用自動貼上後，還會嘗試向先前的應用程式傳送系統貼上快速鍵。常用內容可以加入收藏，避免在清理一般歷史時遺失。", protectionTitle: "3. 隱私保護", protectionText: "在設定中啟用敏感內容保護，可忽略帶有敏感標記的剪貼簿內容，並依應用程式名稱或識別碼加入排除項目。你可以隨時暫停監聽或清除歷史。", syncTitle: "4. 匯入、匯出與同步", syncText: "使用「匯入/匯出」備份或還原本機歷史。Mac App Store 版本還可主動啟用私人 iCloud 同步；同步只包含文字與圖片歷史，不包含檔案項目、檔案路徑或來源應用程式資訊。", supportTitle: "5. 取得支援", supportText: "遇到問題時請查看<a data-local-link href=\"support.html\">說明與意見回饋</a>。如需聯絡支援，請寄信至 <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>，並避免附上不必要的敏感剪貼簿內容。" },
  privacy: { title: "CopyManager 隱私權政策", description: "CopyManager 隱私權政策：瞭解剪貼簿資料、本機儲存、網路請求與選用的 iCloud 同步。", eyebrow: "隱私權政策", heading: "CopyManager 隱私權政策", meta: "生效日期：2026 年 7 月 18 日 · 更新日期：2026 年 7 月 25 日", intro: "CopyManager（以下簡稱「本軟體」）是一款跨平台剪貼簿歷史管理工具。本政策說明本軟體在提供剪貼簿記錄、搜尋、預覽、自動貼上、意見回饋及相關功能時如何處理資料。", clipboardTitle: "1. 剪貼簿資料", clipboardText: "本軟體執行並啟用剪貼簿監聽時，會處理你主動複製的文字、圖片、本機檔案路徑以及來源應用程式名稱。帶有密碼管理器或暫存剪貼簿敏感標記的內容會被忽略；你也可以設定其他要排除的應用程式。", storageTitle: "2. 本機儲存", storageText: "預設情況下，剪貼簿歷史儲存在你的本機裝置。文字和中繼資料儲存在 SQLite 資料庫，圖片原檔儲存在本機媒體目錄。你可以隨時暫停監聽、刪除單一項目或清除歷史；解除安裝本軟體或刪除相關本機資料會移除裝置上的歷史。", icloudTitle: "3. 選用的 iCloud 同步", icloudText: "Mac App Store 版本允許你主動啟用 iCloud 同步。啟用後，文字和圖片歷史會儲存到你的私人 CloudKit 資料庫，以便在使用同一 Apple 帳號的裝置間同步；檔案項目、檔案路徑和來源應用程式資訊不會上傳。iCloud 與 CloudKit 由 Apple 依其政策處理。直接下載版本不提供 iCloud 同步。", networkTitle: "4. 網路請求與支援資料", network1: "你主動提交意見回饋時，姓名（選填）、電子郵件、回饋內容、軟體版本和作業系統版本會傳送到 CopyManager 支援服務。", network2: "直接下載版本會存取 CopyManager 服務進行授權驗證和更新檢查，並每日傳送一次活動記錄，其中包含隨機安裝 ID、作業系統、CPU 架構、軟體版本及存在時的啟用碼。", network3: "Mac App Store 版本使用 Apple StoreKit 處理購買，不包含直接下載版授權、自動更新和活動回報功能。", networkText: "上述請求不包含剪貼簿內容。我們不會出售剪貼簿資料，也不使用第三方廣告或跨應用程式追蹤 SDK。", permissionsTitle: "5. 系統權限", permissionsText: "自動貼上是選用功能。在 macOS 上，只有使用此功能時才需要「輔助使用」權限，以傳送貼上快速鍵。拒絕此權限不會影響複製和剪貼簿歷史功能。", choicesTitle: "6. 你的選擇", choicesText: "你可以暫停剪貼簿監聽、關閉敏感內容保護或 iCloud 同步、清理歷史記錄，並透過系統設定撤銷相關權限。提交意見回饋前，可以先移除不想傳送的資訊。", updatesTitle: "7. 政策更新", updatesText: "如果功能或資料處理方式發生變更，本政策可能會相應更新，並在本頁標示更新日期。", contactTitle: "8. 聯絡我們", contactText: "如對本政策或資料處理有疑問，請寄信至 <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>，或查看<a data-local-link href=\"support.html\">說明與意見回饋</a>。" },
  terms: { title: "CopyManager 使用者協議", description: "CopyManager 使用者協議。", eyebrow: "使用者協議", heading: "CopyManager 使用者協議", meta: "生效日期：2025 年 12 月 18 日 · 更新日期：2026 年 7 月 25 日", intro: "使用 CopyManager（以下簡稱「本軟體」）前，請仔細閱讀本協議。下載、安裝或使用本軟體即表示你同意本協議；如不同意，請停止使用。", serviceTitle: "1. 服務說明", serviceText: "本軟體提供剪貼簿歷史、搜尋、收藏、預覽、自動貼上、匯入匯出，以及特定版本中的授權、購買或 iCloud 同步功能。實際功能可能因軟體版本、作業系統、系統權限、裝置能力和相關服務狀態而異。", rulesTitle: "2. 使用規則", rulesText: "你應合法使用本軟體，並對自行複製、儲存、處理或分享的內容負責。不得利用本軟體侵犯他人權利、違反適用法律、干擾軟體或相關服務正常運作，亦不得從事法律禁止的攻擊或濫用。", contentTitle: "3. 剪貼簿內容與備份", contentText: "剪貼簿歷史可能包含密碼、個人資訊或其他敏感內容。你應自行決定適合儲存的內容，定期清理敏感記錄並保留必要備份。刪除歷史、本機資料庫、應用程式資料或雲端資料前，請先確認已保留所需內容。", autopasteTitle: "4. 自動貼上與平台限制", autopasteText: "自動貼上依賴作業系統權限、目前焦點視窗和平台輸入能力。macOS 需要「輔助使用」權限；Linux Wayland 可能需要額外工具且受系統限制。本軟體不保證自動貼上在所有應用程式、裝置或系統環境中皆可用。", purchaseTitle: "5. 購買、授權與退款", purchaseText: "直接下載版本的付費功能、授權和購買受購買頁面所示規則約束。Mac App Store 版本透過 Apple StoreKit 處理購買與回復購買，交易和退款適用 Apple 的相關條款。購買前請確認版本、平台和授權範圍。", licenseTitle: "6. 開放原始碼授權與智慧財產權", licenseText: "本軟體原始碼及第三方元件分別受隨附的開放原始碼授權和第三方授權約束；這些授權所賦予的權利不受本協議限制。CopyManager 的名稱、圖形及未依開放原始碼授權提供的材料受適用智慧財產權法律保護。", disclaimerTitle: "7. 免責聲明與責任限制", disclaimerText: "在適用法律允許的最大範圍內，本軟體按「現狀」和「可用」狀態提供，不承諾永不中斷、完全無誤或符合所有特定用途。對於因裝置故障、誤操作、權限限制、第三方服務異常或不可抗力造成的資料遺失、貼上失敗或其他損失，開發者僅在法律規定範圍內承擔責任。", updatesTitle: "8. 協議更新與停止使用", updatesText: "我們可能因功能、法律或營運變更更新本協議，並在本頁標示更新日期。你可隨時停止使用並解除安裝本軟體。", contactTitle: "9. 聯絡我們", contactText: "如對本協議有疑問，請寄信至 <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>，或查看<a data-local-link href=\"support.html\">說明與意見回饋</a>。" },
  support: { title: "CopyManager 說明與意見回饋", description: "CopyManager 說明與意見回饋：剪貼簿監聽、自動貼上、歷史資料與常見問題。", eyebrow: "支援", heading: "CopyManager 說明與意見回饋", meta: "更新日期：2026 年 7 月 25 日", captureTitle: "為什麼沒有記錄複製內容？", captureText: "請確認 CopyManager 正在執行且剪貼簿監聽未暫停。密碼管理器、帶有敏感或暫存標記的內容，以及你在設定中排除的應用程式不會寫入歷史。", autopasteTitle: "為什麼自動貼上沒有作用？", autopasteText: "macOS 使用者需在「系統設定 → 隱私權與安全性 → 輔助使用」中允許 CopyManager。Linux X11 使用 XTest；Wayland 環境需要可用的 <code>wtype</code> 或 <code>ydotool</code>，且仍可能受桌面環境安全政策限制。即使無法自動貼上，複製到系統剪貼簿仍可正常使用。", storageTitle: "歷史資料儲存在哪裡？", storageText: "文字和中繼資料儲存在本機 SQLite 資料庫，圖片儲存在本機媒體目錄。你可以使用應用程式內的匯入/匯出功能備份和還原歷史。Mac App Store 版本還可主動啟用私人 iCloud 同步。", deleteTitle: "如何刪除資料？", deleteText: "你可以在應用程式中刪除單一項目、依規則自動清理或清除歷史。執行不可復原的清理前，請先匯出需要保留的資料。", contactTitle: "聯絡支援", contactText: "請寄信至 <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>，並說明作業系統、CopyManager 版本、問題發生時間和重現步驟。請勿傳送密碼、權杖或不必要的私人剪貼簿內容。", relatedTitle: "相關文件", relatedText: "你還可以查看<a data-local-link href=\"user-guide.html\">使用說明</a>、<a data-local-link href=\"privacy-policy.html\">隱私權政策</a>和<a data-local-link href=\"terms-of-service.html\">使用者協議</a>。" }
};

translations.es = {
  common: { homeLabel: "Inicio de App Pages", back: "← Volver a CopyManager", languageLabel: "Elegir idioma", copyright: "© 2026 CopyManager" },
  home: { title: "CopyManager · Documentación y soporte", description: "Guía, privacidad, términos y soporte de CopyManager.", eyebrow: "LOCAL PRIMERO", heading: "Todo lo que copiaste,<br>cuando lo necesites.", lead: "Historial multiplataforma, búsqueda, favoritos, vista previa y pegado automático, guardados localmente de forma predeterminada.", viewDocuments: "Ver documentos", documentsEyebrow: "DOCUMENTOS", documentsTitle: "Documentación y soporte", guideTitle: "Guía de uso", guideText: "Primeros pasos, funciones y permisos", privacyTitle: "Política de privacidad", privacyText: "Datos del portapapeles, red y sincronización con iCloud", termsTitle: "Términos de servicio", termsText: "Reglas, límites del servicio y responsabilidad", supportTitle: "Obtener ayuda", supportText: "Preguntas frecuentes, diagnóstico y contacto" },
  guide: { title: "Guía de CopyManager", description: "Guía de uso de CopyManager.", eyebrow: "GUÍA DE USO", heading: "Guía de CopyManager", meta: "Actualizado: 25 de julio de 2026", startTitle: "1. Primeros pasos", startText: "Tras iniciar CopyManager, copia texto, imágenes o archivos para crear el historial. Abre la ventana con el atajo global y encuentra contenido por búsqueda, tipo o aplicación de origen.", pasteTitle: "2. Pegado y favoritos", pasteText: "Al elegir un elemento vuelve al portapapeles. Con el pegado automático, CopyManager intenta enviar el atajo de pegar a la aplicación anterior. Añade contenido frecuente a favoritos para conservarlo al limpiar el historial.", protectionTitle: "3. Protección de la privacidad", protectionText: "Activa la protección de contenido sensible y excluye aplicaciones por nombre o identificador en Ajustes. Puedes pausar la supervisión o borrar el historial cuando quieras.", syncTitle: "4. Importación, exportación y sincronización", syncText: "Usa Importar/Exportar para respaldar o restaurar el historial local. La versión de Mac App Store permite sincronización privada con iCloud de texto e imágenes, nunca de archivos, rutas ni aplicación de origen.", supportTitle: "5. Obtener ayuda", supportText: "Consulta <a data-local-link href=\"support.html\">Ayuda y comentarios</a> o escribe a <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> sin adjuntar contenido sensible innecesario." },
  privacy: { title: "Política de privacidad de CopyManager", description: "Privacidad de CopyManager: datos, almacenamiento local, red e iCloud opcional.", eyebrow: "POLÍTICA DE PRIVACIDAD", heading: "Política de privacidad de CopyManager", meta: "Vigente: 18 de julio de 2026 · Actualizado: 25 de julio de 2026", intro: "CopyManager (el «Software») gestiona el historial del portapapeles en varias plataformas. Esta política explica el tratamiento de datos al capturar, buscar, previsualizar, pegar automáticamente y recibir comentarios.", clipboardTitle: "1. Datos del portapapeles", clipboardText: "Con la supervisión activa, procesa texto, imágenes, rutas de archivos locales y nombres de aplicaciones que copias. Ignora contenido marcado como sensible o temporal; también puedes excluir aplicaciones.", storageTitle: "2. Almacenamiento local", storageText: "El historial se guarda localmente: texto y metadatos en SQLite e imágenes en una carpeta multimedia. Puedes pausar, borrar elementos o vaciar el historial. Desinstalar o borrar los datos locales elimina el historial del dispositivo.", icloudTitle: "3. Sincronización opcional con iCloud", icloudText: "La versión de Mac App Store permite guardar texto e imágenes en tu base privada de CloudKit para sincronizarlos entre dispositivos con la misma cuenta Apple. No sube archivos, rutas ni aplicaciones de origen. Apple gestiona iCloud y CloudKit. La versión directa no incluye esta función.", networkTitle: "4. Solicitudes de red y soporte", network1: "Al enviar comentarios se remiten al soporte el nombre opcional, correo, mensaje y versiones del software y del sistema.", network2: "La versión directa contacta con CopyManager para validar licencias y buscar actualizaciones, y envía a diario un ID de instalación aleatorio, sistema, arquitectura, versión y código de activación si existe.", network3: "La versión de Mac App Store usa StoreKit y no incluye licencia directa, actualización propia ni informe de actividad.", networkText: "Estas solicitudes no contienen el portapapeles. No vendemos sus datos ni usamos publicidad o seguimiento entre aplicaciones.", permissionsTitle: "5. Permisos del sistema", permissionsText: "El pegado automático es opcional. En macOS solo necesita Accesibilidad para enviar el atajo de pegar; denegarla no afecta a la copia ni al historial.", choicesTitle: "6. Tus opciones", choicesText: "Puedes pausar la supervisión, desactivar la protección o iCloud, limpiar el historial y revocar permisos. Elimina del comentario cualquier dato que no quieras enviar.", updatesTitle: "7. Cambios de la política", updatesText: "Si cambian las funciones o el tratamiento, actualizaremos esta política y su fecha.", contactTitle: "8. Contacto", contactText: "Escribe a <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> o visita <a data-local-link href=\"support.html\">Ayuda y comentarios</a>." },
  terms: { title: "Términos de servicio de CopyManager", description: "Términos de servicio de CopyManager.", eyebrow: "TÉRMINOS DE SERVICIO", heading: "Términos de servicio de CopyManager", meta: "Vigente: 18 de diciembre de 2025 · Actualizado: 25 de julio de 2026", intro: "Lee estos términos antes de usar CopyManager. Al descargarlo, instalarlo o usarlo los aceptas; si no estás de acuerdo, deja de usarlo.", serviceTitle: "1. Descripción del servicio", serviceText: "El Software ofrece historial, búsqueda, favoritos, vista previa, pegado automático, importación y exportación, además de licencia, compras o iCloud en ciertas versiones. Las funciones dependen de la versión, sistema, permisos, dispositivo y servicios.", rulesTitle: "2. Reglas de uso", rulesText: "Úsalo legalmente y responsabilízate del contenido que copies, guardes, proceses o compartas. No infrinjas derechos o leyes ni perturbes o ataques el Software o sus servicios.", contentTitle: "3. Contenido y copias de seguridad", contentText: "El historial puede contener contraseñas o datos sensibles. Decide qué guardar, limpia registros sensibles y conserva copias. Antes de borrar datos locales o en la nube, comprueba que conservas lo necesario.", autopasteTitle: "4. Pegado automático y límites", autopasteText: "Depende de permisos, ventana activa y capacidades de entrada. macOS exige Accesibilidad y Wayland puede requerir herramientas adicionales. No se garantiza en todas las aplicaciones o sistemas.", purchaseTitle: "5. Compras, licencias y reembolsos", purchaseText: "La versión directa sigue las reglas de su página de compra. Mac App Store usa StoreKit y se rige por los términos de Apple para pagos y reembolsos. Comprueba versión, plataforma y alcance antes de comprar.", licenseTitle: "6. Código abierto y propiedad intelectual", licenseText: "El código y componentes se rigen por sus licencias incluidas. Estas condiciones no limitan esos derechos. El nombre, gráficos y materiales no abiertos de CopyManager están protegidos por la ley.", disclaimerTitle: "7. Exención y límite de responsabilidad", disclaimerText: "En la medida permitida por la ley, se ofrece «tal cual» y «según disponibilidad», sin garantía de continuidad, ausencia de errores o idoneidad. El desarrollador solo responde en lo exigido por ley por pérdidas debidas a fallos, errores, permisos, terceros o fuerza mayor.", updatesTitle: "8. Cambios y cese de uso", updatesText: "Podemos actualizar estos términos por cambios funcionales, legales u operativos e indicaremos la fecha. Puedes desinstalar el Software cuando quieras.", contactTitle: "9. Contacto", contactText: "Escribe a <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> o visita <a data-local-link href=\"support.html\">Ayuda y comentarios</a>." },
  support: { title: "Ayuda y comentarios de CopyManager", description: "Ayuda sobre supervisión, pegado automático e historial de CopyManager.", eyebrow: "SOPORTE", heading: "Ayuda y comentarios de CopyManager", meta: "Actualizado: 25 de julio de 2026", captureTitle: "¿Por qué no se registra lo copiado?", captureText: "Comprueba que CopyManager está activo y la supervisión no está pausada. Gestores de contraseñas, contenido sensible o temporal y aplicaciones excluidas no se guardan.", autopasteTitle: "¿Por qué no funciona el pegado automático?", autopasteText: "En macOS permite CopyManager en Ajustes del Sistema → Privacidad y seguridad → Accesibilidad. X11 usa XTest; Wayland necesita <code>wtype</code> o <code>ydotool</code> y puede tener restricciones. Copiar al portapapeles sigue funcionando.", storageTitle: "¿Dónde se guarda el historial?", storageText: "Texto y metadatos se guardan en SQLite e imágenes en una carpeta local. Importar/Exportar permite respaldar y restaurar. Mac App Store también ofrece iCloud privado.", deleteTitle: "¿Cómo elimino los datos?", deleteText: "Borra elementos, aplica limpieza por reglas o vacía el historial. Exporta lo que quieras conservar antes de una limpieza irreversible.", contactTitle: "Contactar con soporte", contactText: "Escribe a <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> indicando sistema, versión, hora y pasos. No envíes contraseñas, tokens ni contenido privado innecesario.", relatedTitle: "Documentos relacionados", relatedText: "Consulta la <a data-local-link href=\"user-guide.html\">Guía</a>, la <a data-local-link href=\"privacy-policy.html\">Política de privacidad</a> y los <a data-local-link href=\"terms-of-service.html\">Términos</a>." }
};

const localeOverrides = {
  fr: {
    common: { homeLabel: "Accueil App Pages", back: "← Retour à CopyManager", languageLabel: "Choisir la langue" },
    home: { title: "CopyManager · Documentation et assistance", description: "Guide, confidentialité, conditions et assistance de CopyManager.", eyebrow: "LOCAL D’ABORD", heading: "Tout ce que vous copiez,<br>toujours à portée de main.", lead: "Historique multiplateforme, recherche, favoris, aperçu et collage automatique, stockés localement par défaut.", viewDocuments: "Voir les documents", documentsEyebrow: "DOCUMENTS", documentsTitle: "Documentation et assistance", guideTitle: "Guide d’utilisation", guideText: "Prise en main, fonctions et autorisations", privacyTitle: "Politique de confidentialité", privacyText: "Données, réseau et synchronisation iCloud", termsTitle: "Conditions d’utilisation", termsText: "Règles, limites du service et responsabilité", supportTitle: "Obtenir de l’aide", supportText: "FAQ, dépannage et contact" },
    guide: { title: "Guide de CopyManager", description: "Guide d’utilisation de CopyManager.", eyebrow: "GUIDE D’UTILISATION", heading: "Guide de CopyManager", meta: "Mis à jour le 25 juillet 2026", startTitle: "1. Prise en main", startText: "Après le lancement, copiez du texte, des images ou des fichiers pour créer l’historique. Ouvrez la fenêtre avec le raccourci global puis recherchez par contenu, type ou application source.", pasteTitle: "2. Collage et favoris", pasteText: "Sélectionner un élément le replace dans le presse-papiers. Le collage automatique tente aussi d’envoyer le raccourci à l’application précédente. Ajoutez les contenus fréquents aux favoris pour les conserver.", protectionTitle: "3. Protection de la vie privée", protectionText: "Activez la protection du contenu sensible et excluez des applications dans les Réglages. Vous pouvez suspendre la surveillance ou effacer l’historique à tout moment.", syncTitle: "4. Importation, exportation et synchronisation", syncText: "Importez ou exportez l’historique local. La version Mac App Store peut synchroniser en privé textes et images via iCloud, jamais les fichiers, chemins ou applications sources.", supportTitle: "5. Obtenir de l’aide", supportText: "Consultez <a data-local-link href=\"support.html\">Aide et commentaires</a> ou écrivez à <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> sans joindre de contenu sensible inutile." },
    privacy: { title: "Politique de confidentialité de CopyManager", description: "Confidentialité de CopyManager : données, stockage local, réseau et iCloud facultatif.", eyebrow: "POLITIQUE DE CONFIDENTIALITÉ", heading: "Politique de confidentialité de CopyManager", meta: "En vigueur le 18 juillet 2026 · Mis à jour le 25 juillet 2026", clipboardTitle: "1. Données du presse-papiers", storageTitle: "2. Stockage local", icloudTitle: "3. Synchronisation iCloud facultative", networkTitle: "4. Requêtes réseau et données d’assistance", permissionsTitle: "5. Autorisations système", choicesTitle: "6. Vos choix", updatesTitle: "7. Mises à jour de la politique", contactTitle: "8. Nous contacter", contactText: "Écrivez à <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> ou consultez <a data-local-link href=\"support.html\">Aide et commentaires</a>." },
    terms: { title: "Conditions d’utilisation de CopyManager", description: "Conditions d’utilisation de CopyManager.", eyebrow: "CONDITIONS D’UTILISATION", heading: "Conditions d’utilisation de CopyManager", meta: "En vigueur le 18 décembre 2025 · Mis à jour le 25 juillet 2026", serviceTitle: "1. Description du service", rulesTitle: "2. Règles d’utilisation", contentTitle: "3. Contenu et sauvegardes", autopasteTitle: "4. Collage automatique et limites", purchaseTitle: "5. Achats, licences et remboursements", licenseTitle: "6. Open source et propriété intellectuelle", disclaimerTitle: "7. Exclusion et limitation de responsabilité", updatesTitle: "8. Modifications et arrêt", contactTitle: "9. Nous contacter", contactText: "Écrivez à <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> ou consultez <a data-local-link href=\"support.html\">Aide et commentaires</a>." },
    support: { title: "Aide et commentaires CopyManager", description: "Aide sur la surveillance, le collage automatique et l’historique.", eyebrow: "ASSISTANCE", heading: "Aide et commentaires CopyManager", meta: "Mis à jour le 25 juillet 2026", captureTitle: "Pourquoi le contenu copié n’est-il pas enregistré ?", captureText: "Vérifiez que CopyManager fonctionne et que la surveillance n’est pas suspendue. Les gestionnaires de mots de passe, contenus sensibles ou temporaires et applications exclues ne sont pas enregistrés.", autopasteTitle: "Pourquoi le collage automatique ne fonctionne-t-il pas ?", storageTitle: "Où l’historique est-il stocké ?", deleteTitle: "Comment supprimer les données ?", contactTitle: "Contacter l’assistance", relatedTitle: "Documents associés", relatedText: "Consultez le <a data-local-link href=\"user-guide.html\">Guide</a>, la <a data-local-link href=\"privacy-policy.html\">Politique de confidentialité</a> et les <a data-local-link href=\"terms-of-service.html\">Conditions</a>." }
  },
  de: {
    common: { homeLabel: "App-Pages-Startseite", back: "← Zurück zu CopyManager", languageLabel: "Sprache wählen" },
    home: { title: "CopyManager · Dokumentation und Support", description: "Anleitung, Datenschutz, Bedingungen und Support für CopyManager.", eyebrow: "LOKAL ZUERST", heading: "Alles, was du kopierst,<br>jederzeit wieder da.", lead: "Plattformübergreifender Verlauf, Suche, Favoriten, Vorschau und automatisches Einfügen – standardmäßig lokal gespeichert.", viewDocuments: "Dokumente ansehen", documentsEyebrow: "DOKUMENTE", documentsTitle: "Dokumentation und Support", guideTitle: "Benutzerhandbuch", guideText: "Einstieg, Funktionen und Berechtigungen", privacyTitle: "Datenschutzrichtlinie", privacyText: "Zwischenablagedaten, Netzwerk und iCloud", termsTitle: "Nutzungsbedingungen", termsText: "Regeln, Leistungsgrenzen und Haftung", supportTitle: "Support", supportText: "FAQ, Fehlerbehebung und Kontakt" },
    guide: { title: "CopyManager Benutzerhandbuch", description: "Benutzerhandbuch für CopyManager.", eyebrow: "BENUTZERHANDBUCH", heading: "CopyManager Benutzerhandbuch", meta: "Aktualisiert: 25. Juli 2026", startTitle: "1. Erste Schritte", startText: "Kopiere nach dem Start Text, Bilder oder Dateien. Öffne das Hauptfenster per globalem Kürzel und suche nach Inhalt, Typ oder Quellanwendung.", pasteTitle: "2. Einfügen und Favoriten", pasteText: "Ein ausgewählter Eintrag gelangt zurück in die Zwischenablage. Automatisches Einfügen sendet zusätzlich das Einfügekürzel an die vorherige App. Favoriten bleiben bei der normalen Bereinigung erhalten.", protectionTitle: "3. Datenschutz", protectionText: "Aktiviere den Schutz sensibler Inhalte und schließe Apps in den Einstellungen aus. Die Überwachung kann jederzeit pausiert und der Verlauf geleert werden.", syncTitle: "4. Import, Export und Synchronisierung", syncText: "Sichere oder stelle den lokalen Verlauf wieder her. Die Mac-App-Store-Version kann Texte und Bilder privat über iCloud synchronisieren, nicht aber Dateien, Pfade oder Quell-Apps.", supportTitle: "5. Support", supportText: "Siehe <a data-local-link href=\"support.html\">Hilfe und Feedback</a> oder schreibe ohne unnötige sensible Inhalte an <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>." },
    privacy: { title: "CopyManager Datenschutzrichtlinie", description: "Datenschutz: Daten, lokale Speicherung, Netzwerk und optionales iCloud.", eyebrow: "DATENSCHUTZRICHTLINIE", heading: "CopyManager Datenschutzrichtlinie", meta: "Gültig ab 18. Juli 2026 · Aktualisiert am 25. Juli 2026", clipboardTitle: "1. Zwischenablagedaten", storageTitle: "2. Lokale Speicherung", icloudTitle: "3. Optionale iCloud-Synchronisierung", networkTitle: "4. Netzwerkanfragen und Supportdaten", permissionsTitle: "5. Systemberechtigungen", choicesTitle: "6. Deine Wahlmöglichkeiten", updatesTitle: "7. Änderungen der Richtlinie", contactTitle: "8. Kontakt", contactText: "Schreibe an <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> oder besuche <a data-local-link href=\"support.html\">Hilfe und Feedback</a>." },
    terms: { title: "CopyManager Nutzungsbedingungen", description: "Nutzungsbedingungen für CopyManager.", eyebrow: "NUTZUNGSBEDINGUNGEN", heading: "CopyManager Nutzungsbedingungen", meta: "Gültig ab 18. Dezember 2025 · Aktualisiert am 25. Juli 2026", serviceTitle: "1. Leistungsbeschreibung", rulesTitle: "2. Nutzungsregeln", contentTitle: "3. Inhalte und Sicherungen", autopasteTitle: "4. Automatisches Einfügen und Grenzen", purchaseTitle: "5. Käufe, Lizenzen und Erstattungen", licenseTitle: "6. Open Source und geistiges Eigentum", disclaimerTitle: "7. Haftungsausschluss und -begrenzung", updatesTitle: "8. Änderungen und Nutzungsende", contactTitle: "9. Kontakt", contactText: "Schreibe an <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> oder besuche <a data-local-link href=\"support.html\">Hilfe und Feedback</a>." },
    support: { title: "CopyManager Hilfe und Feedback", description: "Hilfe zu Überwachung, automatischem Einfügen und Verlauf.", eyebrow: "SUPPORT", heading: "CopyManager Hilfe und Feedback", meta: "Aktualisiert: 25. Juli 2026", captureTitle: "Warum werden kopierte Inhalte nicht erfasst?", captureText: "Prüfe, ob CopyManager läuft und die Überwachung aktiv ist. Passwortmanager, sensible oder temporäre Inhalte und ausgeschlossene Apps werden nicht gespeichert.", autopasteTitle: "Warum funktioniert automatisches Einfügen nicht?", storageTitle: "Wo wird der Verlauf gespeichert?", deleteTitle: "Wie lösche ich Daten?", contactTitle: "Support kontaktieren", relatedTitle: "Zugehörige Dokumente", relatedText: "Lies das <a data-local-link href=\"user-guide.html\">Handbuch</a>, die <a data-local-link href=\"privacy-policy.html\">Datenschutzrichtlinie</a> und die <a data-local-link href=\"terms-of-service.html\">Nutzungsbedingungen</a>." }
  },
  it: {
    common: { homeLabel: "Home di App Pages", back: "← Torna a CopyManager", languageLabel: "Scegli la lingua" },
    home: { title: "CopyManager · Documentazione e supporto", description: "Guida, privacy, termini e supporto per CopyManager.", eyebrow: "PRIMA IL LOCALE", heading: "Tutto ciò che copi,<br>sempre a portata di mano.", lead: "Cronologia multipiattaforma, ricerca, preferiti, anteprima e incolla automatico, salvati localmente per impostazione predefinita.", viewDocuments: "Vedi documenti", documentsEyebrow: "DOCUMENTI", documentsTitle: "Documentazione e supporto", guideTitle: "Guida utente", guideText: "Primi passi, funzioni e autorizzazioni", privacyTitle: "Informativa sulla privacy", privacyText: "Dati, rete e sincronizzazione iCloud", termsTitle: "Termini di servizio", termsText: "Regole, limiti e responsabilità", supportTitle: "Assistenza", supportText: "FAQ, risoluzione problemi e contatti" },
    guide: { title: "Guida di CopyManager", description: "Guida utente di CopyManager.", eyebrow: "GUIDA UTENTE", heading: "Guida di CopyManager", meta: "Aggiornato: 25 luglio 2026", startTitle: "1. Per iniziare", pasteTitle: "2. Incolla e preferiti", protectionTitle: "3. Protezione della privacy", syncTitle: "4. Importazione, esportazione e sincronizzazione", supportTitle: "5. Assistenza", supportText: "Consulta <a data-local-link href=\"support.html\">Aiuto e feedback</a> o scrivi a <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>." },
    privacy: { title: "Informativa sulla privacy di CopyManager", description: "Privacy: dati, archiviazione locale, rete e iCloud opzionale.", eyebrow: "INFORMATIVA SULLA PRIVACY", heading: "Informativa sulla privacy di CopyManager", meta: "In vigore: 18 luglio 2026 · Aggiornato: 25 luglio 2026", clipboardTitle: "1. Dati degli appunti", storageTitle: "2. Archiviazione locale", icloudTitle: "3. Sincronizzazione iCloud opzionale", networkTitle: "4. Richieste di rete e dati di supporto", permissionsTitle: "5. Autorizzazioni di sistema", choicesTitle: "6. Le tue scelte", updatesTitle: "7. Aggiornamenti", contactTitle: "8. Contatti", contactText: "Scrivi a <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> o visita <a data-local-link href=\"support.html\">Aiuto e feedback</a>." },
    terms: { title: "Termini di servizio di CopyManager", description: "Termini di servizio di CopyManager.", eyebrow: "TERMINI DI SERVIZIO", heading: "Termini di servizio di CopyManager", meta: "In vigore: 18 dicembre 2025 · Aggiornato: 25 luglio 2026", serviceTitle: "1. Descrizione del servizio", rulesTitle: "2. Regole d’uso", contentTitle: "3. Contenuti e backup", autopasteTitle: "4. Incolla automatico e limiti", purchaseTitle: "5. Acquisti, licenze e rimborsi", licenseTitle: "6. Open source e proprietà intellettuale", disclaimerTitle: "7. Esclusione e limite di responsabilità", updatesTitle: "8. Aggiornamenti e cessazione", contactTitle: "9. Contatti", contactText: "Scrivi a <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> o visita <a data-local-link href=\"support.html\">Aiuto e feedback</a>." },
    support: { title: "Aiuto e feedback CopyManager", description: "Aiuto su monitoraggio, incolla automatico e cronologia.", eyebrow: "ASSISTENZA", heading: "Aiuto e feedback CopyManager", meta: "Aggiornato: 25 luglio 2026", captureTitle: "Perché i contenuti copiati non vengono registrati?", autopasteTitle: "Perché l’incolla automatico non funziona?", storageTitle: "Dove viene salvata la cronologia?", deleteTitle: "Come elimino i dati?", contactTitle: "Contatta l’assistenza", relatedTitle: "Documenti correlati", relatedText: "Consulta la <a data-local-link href=\"user-guide.html\">Guida</a>, l’<a data-local-link href=\"privacy-policy.html\">Informativa sulla privacy</a> e i <a data-local-link href=\"terms-of-service.html\">Termini</a>." }
  }
};

Object.assign(localeOverrides, {
  ja: {
    common: { homeLabel: "App Pages ホーム", back: "← CopyManager に戻る", languageLabel: "言語を選択" },
    home: { title: "CopyManager · ドキュメントとサポート", description: "CopyManagerのガイド、プライバシー、規約、サポート情報。", eyebrow: "ローカルファースト", heading: "コピーしたすべてを、<br>必要なときに。", lead: "履歴、検索、お気に入り、プレビュー、自動貼り付けに対応し、データは既定で端末内に保存されます。", viewDocuments: "ドキュメントを見る", documentsEyebrow: "ドキュメント", documentsTitle: "ドキュメントとサポート", guideTitle: "ユーザーガイド", guideText: "基本操作、主な機能、権限", privacyTitle: "プライバシーポリシー", privacyText: "クリップボードデータ、通信、iCloud同期", termsTitle: "利用規約", termsText: "利用ルール、サービス範囲、責任", supportTitle: "サポート", supportText: "よくある質問、トラブル解決、お問い合わせ" },
    guide: { title: "CopyManager ユーザーガイド", description: "CopyManagerユーザーガイド。", eyebrow: "ユーザーガイド", heading: "CopyManager ユーザーガイド", meta: "更新日：2026年7月25日", startTitle: "1. はじめに", startText: "CopyManagerを起動し、テキスト、画像、ファイルを通常どおりコピーすると履歴が作成されます。グローバルショートカットで開き、検索、種類、コピー元アプリで絞り込めます。", pasteTitle: "2. 貼り付けとお気に入り", pasteText: "履歴を選ぶとシステムのクリップボードに戻ります。自動貼り付けを有効にすると、直前のアプリへ貼り付け操作も送信します。よく使う内容はお気に入りに保存できます。", protectionTitle: "3. プライバシー保護", protectionText: "設定で機密コンテンツ保護を有効にし、アプリ名や識別子で除外できます。監視の一時停止や履歴の消去はいつでも行えます。", syncTitle: "4. インポート、エクスポート、同期", syncText: "ローカル履歴をバックアップまたは復元できます。Mac App Store版ではテキストと画像だけを非公開iCloud同期でき、ファイル、パス、コピー元情報は同期しません。", supportTitle: "5. サポート", supportText: "<a data-local-link href=\"support.html\">ヘルプとフィードバック</a>を確認するか、機密情報を添付せず<a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>へご連絡ください。" },
    privacy: { title: "CopyManager プライバシーポリシー", description: "データ、端末内保存、通信、任意のiCloud同期について。", eyebrow: "プライバシーポリシー", heading: "CopyManager プライバシーポリシー", meta: "発効日：2026年7月18日 · 更新日：2026年7月25日", clipboardTitle: "1. クリップボードデータ", storageTitle: "2. 端末内保存", icloudTitle: "3. 任意のiCloud同期", networkTitle: "4. 通信とサポートデータ", permissionsTitle: "5. システム権限", choicesTitle: "6. ユーザーの選択", updatesTitle: "7. ポリシーの更新", contactTitle: "8. お問い合わせ", contactText: "<a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>へメールするか、<a data-local-link href=\"support.html\">ヘルプとフィードバック</a>をご覧ください。" },
    terms: { title: "CopyManager 利用規約", description: "CopyManager利用規約。", eyebrow: "利用規約", heading: "CopyManager 利用規約", meta: "発効日：2025年12月18日 · 更新日：2026年7月25日", serviceTitle: "1. サービス内容", rulesTitle: "2. 利用ルール", contentTitle: "3. クリップボード内容とバックアップ", autopasteTitle: "4. 自動貼り付けと制限", purchaseTitle: "5. 購入、ライセンス、返金", licenseTitle: "6. オープンソースと知的財産", disclaimerTitle: "7. 免責および責任制限", updatesTitle: "8. 規約更新と利用停止", contactTitle: "9. お問い合わせ", contactText: "<a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>へメールするか、<a data-local-link href=\"support.html\">ヘルプとフィードバック</a>をご覧ください。" },
    support: { title: "CopyManager ヘルプとフィードバック", description: "監視、自動貼り付け、履歴に関するヘルプ。", eyebrow: "サポート", heading: "CopyManager ヘルプとフィードバック", meta: "更新日：2026年7月25日", captureTitle: "コピーした内容が記録されないのはなぜですか？", autopasteTitle: "自動貼り付けが動作しないのはなぜですか？", storageTitle: "履歴はどこに保存されますか？", deleteTitle: "データを削除するには？", contactTitle: "サポートへのお問い合わせ", relatedTitle: "関連ドキュメント", relatedText: "<a data-local-link href=\"user-guide.html\">ユーザーガイド</a>、<a data-local-link href=\"privacy-policy.html\">プライバシーポリシー</a>、<a data-local-link href=\"terms-of-service.html\">利用規約</a>もご覧ください。" }
  },
  ko: {
    common: { homeLabel: "App Pages 홈", back: "← CopyManager로 돌아가기", languageLabel: "언어 선택" },
    home: { title: "CopyManager · 문서 및 지원", description: "CopyManager 사용 안내, 개인정보 처리방침, 약관 및 지원 정보입니다.", eyebrow: "로컬 우선", heading: "복사한 모든 내용을,<br>필요할 때 다시.", lead: "플랫폼 간 클립보드 기록, 검색, 즐겨찾기, 미리보기 및 자동 붙여넣기를 제공하며 기본적으로 기기에 저장합니다.", viewDocuments: "문서 보기", documentsEyebrow: "문서", documentsTitle: "문서 및 지원", guideTitle: "사용 안내", guideText: "시작하기, 핵심 기능 및 권한", privacyTitle: "개인정보 처리방침", privacyText: "클립보드 데이터, 네트워크 및 iCloud 동기화", termsTitle: "서비스 약관", termsText: "사용 규칙, 서비스 범위 및 책임", supportTitle: "지원 받기", supportText: "자주 묻는 질문, 문제 해결 및 문의" },
    guide: { title: "CopyManager 사용 안내", description: "CopyManager 사용 안내입니다.", eyebrow: "사용 안내", heading: "CopyManager 사용 안내", meta: "업데이트: 2026년 7월 25일", startTitle: "1. 시작하기", pasteTitle: "2. 붙여넣기 및 즐겨찾기", protectionTitle: "3. 개인정보 보호", syncTitle: "4. 가져오기, 내보내기 및 동기화", supportTitle: "5. 지원 받기", supportText: "<a data-local-link href=\"support.html\">도움말 및 피드백</a>을 확인하거나 민감한 내용을 제외하고 <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>으로 문의하세요." },
    privacy: { title: "CopyManager 개인정보 처리방침", description: "데이터, 로컬 저장, 네트워크 및 선택적 iCloud 동기화 안내.", eyebrow: "개인정보 처리방침", heading: "CopyManager 개인정보 처리방침", meta: "시행일: 2026년 7월 18일 · 업데이트: 2026년 7월 25일", clipboardTitle: "1. 클립보드 데이터", storageTitle: "2. 로컬 저장", icloudTitle: "3. 선택적 iCloud 동기화", networkTitle: "4. 네트워크 요청 및 지원 데이터", permissionsTitle: "5. 시스템 권한", choicesTitle: "6. 사용자의 선택", updatesTitle: "7. 방침 업데이트", contactTitle: "8. 문의하기", contactText: "<a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>으로 이메일을 보내거나 <a data-local-link href=\"support.html\">도움말 및 피드백</a>을 확인하세요." },
    terms: { title: "CopyManager 서비스 약관", description: "CopyManager 서비스 약관입니다.", eyebrow: "서비스 약관", heading: "CopyManager 서비스 약관", meta: "시행일: 2025년 12월 18일 · 업데이트: 2026년 7월 25일", serviceTitle: "1. 서비스 설명", rulesTitle: "2. 사용 규칙", contentTitle: "3. 클립보드 내용 및 백업", autopasteTitle: "4. 자동 붙여넣기 및 플랫폼 제한", purchaseTitle: "5. 구매, 라이선스 및 환불", licenseTitle: "6. 오픈 소스 및 지식 재산권", disclaimerTitle: "7. 면책 및 책임 제한", updatesTitle: "8. 약관 업데이트 및 사용 중단", contactTitle: "9. 문의하기", contactText: "<a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>으로 이메일을 보내거나 <a data-local-link href=\"support.html\">도움말 및 피드백</a>을 확인하세요." },
    support: { title: "CopyManager 도움말 및 피드백", description: "모니터링, 자동 붙여넣기 및 기록에 관한 도움말.", eyebrow: "지원", heading: "CopyManager 도움말 및 피드백", meta: "업데이트: 2026년 7월 25일", captureTitle: "복사한 내용이 기록되지 않는 이유는 무엇인가요?", autopasteTitle: "자동 붙여넣기가 작동하지 않는 이유는 무엇인가요?", storageTitle: "기록은 어디에 저장되나요?", deleteTitle: "데이터를 삭제하려면 어떻게 하나요?", contactTitle: "지원 문의", relatedTitle: "관련 문서", relatedText: "<a data-local-link href=\"user-guide.html\">사용 안내</a>, <a data-local-link href=\"privacy-policy.html\">개인정보 처리방침</a>, <a data-local-link href=\"terms-of-service.html\">서비스 약관</a>도 확인하세요." }
  },
  pt_BR: {
    common: { homeLabel: "Início do App Pages", back: "← Voltar ao CopyManager", languageLabel: "Escolher idioma" },
    home: { title: "CopyManager · Documentação e suporte", description: "Guia, privacidade, termos e suporte do CopyManager.", eyebrow: "LOCAL PRIMEIRO", heading: "Tudo o que você copiou,<br>quando precisar.", lead: "Histórico multiplataforma, pesquisa, favoritos, prévia e colagem automática, armazenados localmente por padrão.", viewDocuments: "Ver documentos", documentsEyebrow: "DOCUMENTOS", documentsTitle: "Documentação e suporte", guideTitle: "Guia do usuário", guideText: "Primeiros passos, recursos e permissões", privacyTitle: "Política de Privacidade", privacyText: "Dados, rede e sincronização com iCloud", termsTitle: "Termos de Serviço", termsText: "Regras, limites e responsabilidade", supportTitle: "Obter suporte", supportText: "Perguntas frequentes, solução de problemas e contato" },
    guide: { title: "Guia do CopyManager", description: "Guia do usuário do CopyManager.", eyebrow: "GUIA DO USUÁRIO", heading: "Guia do CopyManager", meta: "Atualizado em 25 de julho de 2026", startTitle: "1. Primeiros passos", pasteTitle: "2. Colagem e favoritos", protectionTitle: "3. Proteção de privacidade", syncTitle: "4. Importação, exportação e sincronização", supportTitle: "5. Obter suporte", supportText: "Consulte <a data-local-link href=\"support.html\">Ajuda e feedback</a> ou escreva para <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>." },
    privacy: { title: "Política de Privacidade do CopyManager", description: "Dados, armazenamento local, rede e iCloud opcional.", eyebrow: "POLÍTICA DE PRIVACIDADE", heading: "Política de Privacidade do CopyManager", meta: "Vigente em 18 de julho de 2026 · Atualizado em 25 de julho de 2026", clipboardTitle: "1. Dados da área de transferência", storageTitle: "2. Armazenamento local", icloudTitle: "3. Sincronização opcional com iCloud", networkTitle: "4. Solicitações de rede e dados de suporte", permissionsTitle: "5. Permissões do sistema", choicesTitle: "6. Suas escolhas", updatesTitle: "7. Atualizações da política", contactTitle: "8. Contato", contactText: "Escreva para <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> ou visite <a data-local-link href=\"support.html\">Ajuda e feedback</a>." },
    terms: { title: "Termos de Serviço do CopyManager", description: "Termos de Serviço do CopyManager.", eyebrow: "TERMOS DE SERVIÇO", heading: "Termos de Serviço do CopyManager", meta: "Vigente em 18 de dezembro de 2025 · Atualizado em 25 de julho de 2026", serviceTitle: "1. Descrição do serviço", rulesTitle: "2. Regras de uso", contentTitle: "3. Conteúdo e backups", autopasteTitle: "4. Colagem automática e limites", purchaseTitle: "5. Compras, licenças e reembolsos", licenseTitle: "6. Código aberto e propriedade intelectual", disclaimerTitle: "7. Isenção e limitação de responsabilidade", updatesTitle: "8. Atualizações e fim do uso", contactTitle: "9. Contato", contactText: "Escreva para <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> ou visite <a data-local-link href=\"support.html\">Ajuda e feedback</a>." },
    support: { title: "Ajuda e feedback do CopyManager", description: "Ajuda sobre monitoramento, colagem automática e histórico.", eyebrow: "SUPORTE", heading: "Ajuda e feedback do CopyManager", meta: "Atualizado em 25 de julho de 2026", captureTitle: "Por que o conteúdo copiado não é registrado?", autopasteTitle: "Por que a colagem automática não funciona?", storageTitle: "Onde o histórico é armazenado?", deleteTitle: "Como excluir os dados?", contactTitle: "Contatar o suporte", relatedTitle: "Documentos relacionados", relatedText: "Consulte o <a data-local-link href=\"user-guide.html\">Guia</a>, a <a data-local-link href=\"privacy-policy.html\">Política de Privacidade</a> e os <a data-local-link href=\"terms-of-service.html\">Termos</a>." }
  },
  ru: {
    common: { homeLabel: "Главная App Pages", back: "← Назад к CopyManager", languageLabel: "Выбрать язык" },
    home: { title: "CopyManager · Документация и поддержка", description: "Руководство, конфиденциальность, условия и поддержка CopyManager.", eyebrow: "ЛОКАЛЬНОЕ ХРАНЕНИЕ", heading: "Всё, что вы копировали,<br>всегда под рукой.", lead: "Кроссплатформенная история, поиск, избранное, предпросмотр и автовставка; по умолчанию данные хранятся локально.", viewDocuments: "Открыть документы", documentsEyebrow: "ДОКУМЕНТЫ", documentsTitle: "Документация и поддержка", guideTitle: "Руководство", guideText: "Начало работы, функции и разрешения", privacyTitle: "Политика конфиденциальности", privacyText: "Данные, сеть и синхронизация iCloud", termsTitle: "Условия использования", termsText: "Правила, границы сервиса и ответственность", supportTitle: "Поддержка", supportText: "Вопросы, устранение неполадок и контакты" },
    guide: { title: "Руководство CopyManager", description: "Руководство пользователя CopyManager.", eyebrow: "РУКОВОДСТВО", heading: "Руководство CopyManager", meta: "Обновлено: 25 июля 2026 г.", startTitle: "1. Начало работы", pasteTitle: "2. Вставка и избранное", protectionTitle: "3. Защита конфиденциальности", syncTitle: "4. Импорт, экспорт и синхронизация", supportTitle: "5. Поддержка", supportText: "Откройте <a data-local-link href=\"support.html\">Помощь и отзывы</a> или напишите на <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a>." },
    privacy: { title: "Политика конфиденциальности CopyManager", description: "Данные, локальное хранение, сеть и необязательный iCloud.", eyebrow: "ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ", heading: "Политика конфиденциальности CopyManager", meta: "Действует с 18 июля 2026 г. · Обновлено 25 июля 2026 г.", clipboardTitle: "1. Данные буфера обмена", storageTitle: "2. Локальное хранение", icloudTitle: "3. Необязательная синхронизация iCloud", networkTitle: "4. Сетевые запросы и данные поддержки", permissionsTitle: "5. Системные разрешения", choicesTitle: "6. Ваш выбор", updatesTitle: "7. Обновления политики", contactTitle: "8. Связаться с нами", contactText: "Напишите на <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> или откройте <a data-local-link href=\"support.html\">Помощь и отзывы</a>." },
    terms: { title: "Условия использования CopyManager", description: "Условия использования CopyManager.", eyebrow: "УСЛОВИЯ ИСПОЛЬЗОВАНИЯ", heading: "Условия использования CopyManager", meta: "Действует с 18 декабря 2025 г. · Обновлено 25 июля 2026 г.", serviceTitle: "1. Описание сервиса", rulesTitle: "2. Правила использования", contentTitle: "3. Содержимое и резервные копии", autopasteTitle: "4. Автовставка и ограничения", purchaseTitle: "5. Покупки, лицензии и возвраты", licenseTitle: "6. Открытый код и интеллектуальная собственность", disclaimerTitle: "7. Отказ от гарантий и ограничение ответственности", updatesTitle: "8. Обновления и прекращение использования", contactTitle: "9. Связаться с нами", contactText: "Напишите на <a href=\"mailto:mckejy@gmail.com\">mckejy@gmail.com</a> или откройте <a data-local-link href=\"support.html\">Помощь и отзывы</a>." },
    support: { title: "Помощь и отзывы CopyManager", description: "Помощь по мониторингу, автовставке и истории.", eyebrow: "ПОДДЕРЖКА", heading: "Помощь и отзывы CopyManager", meta: "Обновлено: 25 июля 2026 г.", captureTitle: "Почему скопированное не записывается?", autopasteTitle: "Почему не работает автовставка?", storageTitle: "Где хранится история?", deleteTitle: "Как удалить данные?", contactTitle: "Связаться с поддержкой", relatedTitle: "Связанные документы", relatedText: "Читайте <a data-local-link href=\"user-guide.html\">Руководство</a>, <a data-local-link href=\"privacy-policy.html\">Политику конфиденциальности</a> и <a data-local-link href=\"terms-of-service.html\">Условия</a>." }
  }
});

for (const [language, override] of Object.entries(localeOverrides)) {
  translations[language] = Object.fromEntries(
    Object.keys(translations.en).map((section) => [
      section,
      { ...translations.en[section], ...override[section] }
    ])
  );
}

const languageOptions = [
  ["en", "English", "EN"],
  ["zh_CN", "简体中文", "简"],
  ["zh_TW", "繁體中文", "繁"],
  ["es", "Español", "ES"],
  ["fr", "Français", "FR"],
  ["de", "Deutsch", "DE"],
  ["ja", "日本語", "日"],
  ["ko", "한국어", "한"],
  ["pt_BR", "Português (Brasil)", "PT"],
  ["ru", "Русский", "RU"],
  ["it", "Italiano", "IT"]
];

const supportedLanguages = languageOptions.map(([code]) => code);

function renderLanguageSwitchers() {
  const links = languageOptions.map(([code, name, shortName]) =>
    `<a href="?lang=${code}" data-language="${code}" aria-label="${name}"><span class="language-full">${name}</span><span class="language-short">${shortName}</span></a>`
  ).join("");

  document.querySelectorAll("[data-language-switcher]").forEach((switcher) => {
    switcher.innerHTML = links;
  });
}

function readStoredLanguage() {
  try {
    return localStorage.getItem("copymanager-language");
  } catch {
    return null;
  }
}

function canonicalLanguage(value) {
  if (!value) return null;
  const normalized = value.replace("-", "_").toLowerCase();
  if (normalized === "zh" || normalized.startsWith("zh_cn") || normalized.startsWith("zh_hans")) return "zh_CN";
  if (normalized.startsWith("zh_tw") || normalized.startsWith("zh_hant") || normalized.startsWith("zh_hk") || normalized.startsWith("zh_mo")) return "zh_TW";
  if (normalized === "pt" || normalized.startsWith("pt_")) return "pt_BR";
  const base = normalized.split("_")[0];
  return supportedLanguages.includes(base) ? base : null;
}

function detectLanguage() {
  const requested = canonicalLanguage(new URLSearchParams(location.search).get("lang"));
  if (requested) return requested;

  const stored = canonicalLanguage(readStoredLanguage());
  if (stored) return stored;

  return canonicalLanguage(navigator.language) || "en";
}

function lookup(dictionary, path) {
  return path.split(".").reduce((value, key) => value?.[key], dictionary);
}

function localizeLinks(language) {
  document.querySelectorAll("[data-local-link]").forEach((link) => {
    const url = new URL(link.getAttribute("href"), location.href);
    url.searchParams.set("lang", language);
    link.href = `${url.pathname}${url.search}${url.hash}`;
  });
}

function applyLanguage(language) {
  const dictionary = translations[language];
  const htmlLanguages = { zh_CN: "zh-CN", zh_TW: "zh-TW", pt_BR: "pt-BR" };
  document.documentElement.lang = htmlLanguages[language] || language;

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const value = lookup(dictionary, element.dataset.i18n);
    if (value !== undefined) element.textContent = value;
  });

  document.querySelectorAll("[data-i18n-html]").forEach((element) => {
    const value = lookup(dictionary, element.dataset.i18nHtml);
    if (value !== undefined) element.innerHTML = value;
  });

  document.querySelectorAll("[data-i18n-content]").forEach((element) => {
    const value = lookup(dictionary, element.dataset.i18nContent);
    if (value !== undefined) element.setAttribute("content", value);
  });

  document.querySelectorAll("[data-i18n-aria-label]").forEach((element) => {
    const value = lookup(dictionary, element.dataset.i18nAriaLabel);
    if (value !== undefined) element.setAttribute("aria-label", value);
  });

  document.querySelectorAll("[data-language]").forEach((link) => {
    if (link.dataset.language === language) link.setAttribute("aria-current", "true");
    else link.removeAttribute("aria-current");
  });

  localizeLinks(language);

  try {
    localStorage.setItem("copymanager-language", language);
  } catch {
    // The selected language still applies when storage is unavailable.
  }
}

renderLanguageSwitchers();
applyLanguage(detectLanguage());
